(import (rnrs)
        (mosh test)
        (system)
        (mosh)
        (mosh shell)
        (mosh shell repl))

(test-begin "shell")

(unless (string=? (host-os) "win32")
  (display "IN")
  (flush-output-port (current-output-port))
  (let ()
    (def-command ls)
    ($def-command ls)
     (def-alias ls-x2 ls ls)
     (test-equal ls #f)
     (test-equal (ls -la) #f)
     (test-equal (for-all (lambda (s) (string? s)) $ls) #t)
     (test-equal (begin (cd) (current-directory)) (get-environment-variable "HOME"))
     (test-equal (begin (-> ls (grep main) (grep cpp)) #f) #f)
     (test-equal (string? ($-> ls (grep main) (grep cpp))) #t)
;     (test-equal ls-x2 #f)

))

(test-end)
