(library (mosh jit)
  (export u8*->c-procedure+retq assemble macro-to-fixnum vm-register macro-make-fixnum)
  (import (rnrs) (mosh)
          (match)
          (system)
          (srfi :8)
          (srfi :26)
         (only (srfi :1) append-map drop-right)
          (only (srfi private include) include/resolve)
          (mosh control)
          (only (srfi private include) include/resolve))

  (include/resolve ("mosh" "jit") "jit-impl.ss")
)
