SRCTOP=../..
include $(SRCTOP)/Makefile.inc

TARGET  = MOSH
SOURCES = main.cpp
INSTDIR = $(BINDIR)/SERVERS

INSTDIR    = $(BINDIR)/APPS
ADDLINK    = -lpci -lmonalibc-imp --enable-auto-import
ADDCFLAGS  =
ADDINCLUDE =

SHAREDIR   = $(MONADIR)/share
ifneq ($(BUILD_TARGET),ELF)
include $(SHAREDIR)/configs/monapi-ex5.inc
else
include $(SHAREDIR)/configs/monapi-el5.inc
endif

check-syntax:
	LANG=C $(CXX) -o nul $(CXXFLAGS) $(INCLUDE) -S ${CHK_SOURCES}

-include dependencies
