(import (rnrs)
        (srfi :27)
        (system))

;(display (microseconds))
(random-source-randomize! default-random-source)
(display (random-integer 10))
(newline)
(display (random-integer 10))
(newline)
(display (random-integer 10))
(newline)
(display (random-integer 10))
(newline)
