(import (rnrs)
        (srfi :28)
        )

(display (format "abc ~a" 3))

;(display (microseconds))
;; (random-source-randomize! default-random-source)
;; (display (random-integer 10))
;; (newline)
;; (display (random-integer 10))
;; (newline)
;; (display (random-integer 10))
;; (newline)
;; (display (random-integer 10))
;; (newline)
