(import (rnrs)
        (rnrs eval)
        (mosh string)
        (mosh))

  (define-record-type (tag make-tag tag?))
  (define-record-type (otag make-otag otag?) (opaque #t))
  (define-record-type (stag make-stag stag?) (sealed #t))
  (define-record-type (ostag make-ostag ostag?) (opaque #t) (sealed #t))

(display (equal? (make-tag) (make-tag)))
(newline)
(display (equal? (make-otag) (make-otag)))
(newline)
(display (equal? (make-ostag) (make-ostag)))

;;     (test (eqv? (equal? (make-tag) (make-tag)) (eqv? (make-tag) (make-tag)))
;;           #t)
;;     (test (eqv? (equal? (make-otag) (make-otag)) (eqv? (make-otag) (make-otag)))
;;           #t)
;;     (test (eqv? (equal? (make-stag) (make-stag)) (eqv? (make-stag) (make-stag)))
;;           #t)
;;     (test (eqv? (equal? (make-ostag) (make-ostag)) (eqv? (make-ostag) (make-ostag)))
;;           #t)
