(import (rnrs)
        (mosh)
        (mosh control)
        (mosh test))

(let1 a-pair (annotated-cons 1 2)
  (test-true (annotated-pair? a-pair))
  (test-true (pair? a-pair))
  (test-false (number a-pair))
  (test-eq 1 (car a-pair))
  (test-eq 2 (cdr a-pair)))
(test-results)
