(import (rnrs)
        (mosh)
        (mosh control)
        (mosh test))

(define annotated-cons cons)
(define annotated-pair? pair?)
(define (get-annotation x) #f)
(define (set-annotation! x y) x)

(let1 a-pair (annotated-cons 1 2)
  (test-true (annotated-pair? a-pair))
  (test-true (pair? a-pair))
  (test-false (number? a-pair))
  (test-eq 1 (car a-pair))
  (test-eq 2 (cdr a-pair))
  (test-false (get-annotation a-pair))
  (set-annotation! a-pair 3)
  (test-eq 3 (get-annotation a-pair)))

(test-results)
