;; Generated by misc/scripts/gen-srfi-for-r7rs.scm
(define-library
  (srfi 37)
  (export
    option-processor
    option-optional-arg?
    option-required-arg?
    option-names
    option?
    args-fold
    option)
  (import (srfi :37 args-fold)))
