;; Generated by misc/scripts/gen-srfi-for-r7rs.scm
(define-library
  (srfi 38)
  (export
    write/ss
    write-with-shared-structure
    read/ss
    read-with-shared-structure)
  (import (srfi :38 with-shared-structure)))
