;; Generated by misc/scripts/gen-srfi-for-r7rs.scm
(define-library
  (srfi 99)
  (export
    define-record-type
    record?
    record-rtd
    rtd-name
    rtd-parent
    rtd-field-names
    rtd-all-field-names
    rtd-field-mutable?
    make-rtd
    rtd?
    rtd-constructor
    rtd-predicate
    rtd-accessor
    rtd-mutator)
  (import (srfi :99 records)))
