;;
;;   Copyright (c) 2008  Higepon(Taro Minowa)  <higepon@users.sourceforge.jp>
;;
;;   Redistribution and use in source and binary forms, with or without
;;   modification, are permitted provided that the following conditions
;;   are met:
;;
;;   1. Redistributions of source code must retain the above copyright
;;      notice, this list of conditions and the following disclaimer.
;;
;;   2. Redistributions in binary form must reproduce the above copyright
;;      notice, this list of conditions and the following disclaimer in the
;;      documentation and/or other materials provided with the distribution.
;;
;;   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
;;   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
;;   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
;;   A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
;;   OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
;;   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
;;   TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
;;   PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
;;   LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
;;   NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
;;   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
;;
;; Do not edit this file generated by make-case-data.scm.
;;
(define downcase-alist '(
    (65 . 97) (66 . 98) (67 . 99) (68 . 100) (69 . 101)
    (70 . 102) (71 . 103) (72 . 104) (73 . 105) (80 . 112)
    (81 . 113) (82 . 114) (83 . 115) (84 . 116) (85 . 117)
    (86 . 118) (87 . 119) (88 . 120) (89 . 121) (256 . 257)
    (258 . 259) (260 . 261) (262 . 263) (264 . 265) (272 . 273)
    (274 . 275) (276 . 277) (278 . 279) (280 . 281) (288 . 289)
    (290 . 291) (292 . 293) (294 . 295) (296 . 297) (306 . 307)
    (308 . 309) (310 . 311) (321 . 322) (323 . 324) (325 . 326)
    (327 . 328) (336 . 337) (338 . 339) (340 . 341) (342 . 343)
    (344 . 345) (352 . 353) (354 . 355) (356 . 357) (358 . 359)
    (360 . 361) (368 . 369) (370 . 371) (372 . 373) (374 . 375)
    (385 . 595) (386 . 387) (388 . 389) (390 . 596) (391 . 392)
    (393 . 598) (401 . 402) (403 . 608) (404 . 611) (406 . 617)
    (407 . 616) (408 . 409) (6 . 640) (9 . 643) (7 . 658)
    (6 . 405) (512 . 513) (514 . 515) (516 . 517) (518 . 519)
    (520 . 521) (528 . 529) (530 . 531) (532 . 533) (534 . 535)
    (536 . 537) (546 . 547) (548 . 549) (550 . 551) (552 . 553)
    (560 . 561) (562 . 563) (577 . 578) (579 . 384) (580 . 649)
    (582 . 583) (584 . 585) (1024 . 1104) (1025 . 1105) (1026 . 1106)
    (1027 . 1107) (1028 . 1108) (1029 . 1109) (1030 . 1110) (1031 . 1111)
    (1032 . 1112) (1033 . 1113) (1040 . 1072) (1041 . 1073) (1042 . 1074)
    (1043 . 1075) (1044 . 1076) (1045 . 1077) (1046 . 1078) (1047 . 1079)
    (1048 . 1080) (1049 . 1081) (1056 . 1088) (1057 . 1089) (1058 . 1090)
    (1059 . 1091) (1060 . 1092) (1061 . 1093) (1062 . 1094) (1063 . 1095)
    (1064 . 1096) (1065 . 1097) (1120 . 1121) (1122 . 1123) (1124 . 1125)
    (1126 . 1127) (1128 . 1129) (1136 . 1137) (1138 . 1139) (1140 . 1141)
    (1142 . 1143) (1144 . 1145) (1152 . 1153) (1168 . 1169) (1170 . 1171)
    (1172 . 1173) (1174 . 1175) (1176 . 1177) (1280 . 1281) (1282 . 1283)
    (1284 . 1285) (1286 . 1287) (1288 . 1289) (1296 . 1297) (1298 . 1299)
    (1329 . 1377) (1330 . 1378) (1331 . 1379) (1332 . 1380) (1333 . 1381)
    (1334 . 1382) (1335 . 1383) (1336 . 1384) (1337 . 1385) (1344 . 1392)
    (1345 . 1393) (1346 . 1394) (1347 . 1395) (1348 . 1396) (1349 . 1397)
    (1350 . 1398) (1351 . 1399) (1352 . 1400) (1353 . 1401) (1360 . 1408)
    (1361 . 1409) (1362 . 1410) (1363 . 1411) (1364 . 1412) (1365 . 1413)
    (1366 . 1414) (8544 . 8560) (8545 . 8561) (8546 . 8562) (8547 . 8563)
    (8548 . 8564) (8549 . 8565) (8550 . 8566) (8551 . 8567) (8552 . 8568)
    (8553 . 8569) (8579 . 8580) (66560 . 66600) (66561 . 66601) (66568 . 66608)
    (66569 . 66609) (66576 . 66616) (66577 . 66617) (66584 . 66624) (66585 . 66625)
    (66592 . 66632) (66593 . 66633)))