; This file is automatically generated from the testcases file,
; which is located as a sibling file.  - Do not edit.

(require  (lib "test.ss"    "schemeunit"))
(require  (lib "text-ui.ss" "schemeunit"))

TEST-SETUP-HERE

(test/text-ui
  (make-test-suite
   "Test suite"

   TEST-CASES-HERE

   )
  
)

TEST-TEAR-DOWN-HERE