(load "./bootstrap.gauche/compat-gauche.scm")
(load "./runtime.scm")
(load "./runtime-cache.scm")
(load "./bootstrap.gauche/mosh-stubs.scm")
(load "./mosh-utils5.scm")
(load "./r6rs.gexp")
(load "./system.gexp")
(load "./expander.scm")
(ex:expand-r5rs-file "mosh-exceptions.scm" "mosh-exceptions.exp" (ex:environment '(rnrs) '(nmosh conditions)))
