MOSH_ONIG_DIR=extlibs/onig-5.9.2
ONIG_SRCS= \
$(MOSH_ONIG_DIR)/regint.h \
$(MOSH_ONIG_DIR)/regparse.h \
$(MOSH_ONIG_DIR)/regenc.h \
$(MOSH_ONIG_DIR)/st.h \
$(MOSH_ONIG_DIR)/regerror.c \
$(MOSH_ONIG_DIR)/regparse.c \
$(MOSH_ONIG_DIR)/regext.c \
$(MOSH_ONIG_DIR)/regcomp.c \
$(MOSH_ONIG_DIR)/regexec.c \
$(MOSH_ONIG_DIR)/reggnu.c \
$(MOSH_ONIG_DIR)/regenc.c \
$(MOSH_ONIG_DIR)/regsyntax.c \
$(MOSH_ONIG_DIR)/regtrav.c \
$(MOSH_ONIG_DIR)/regversion.c \
$(MOSH_ONIG_DIR)/st.c \
$(MOSH_ONIG_DIR)/regposix.c \
$(MOSH_ONIG_DIR)/regposerr.c \
$(MOSH_ONIG_DIR)/enc/unicode.c \
$(MOSH_ONIG_DIR)/enc/ascii.c \
$(MOSH_ONIG_DIR)/enc/utf8.c \
$(MOSH_ONIG_DIR)/enc/utf16_be.c \
$(MOSH_ONIG_DIR)/enc/utf16_le.c \
$(MOSH_ONIG_DIR)/enc/utf32_be.c \
$(MOSH_ONIG_DIR)/enc/utf32_le.c \
$(MOSH_ONIG_DIR)/enc/euc_jp.c \
$(MOSH_ONIG_DIR)/enc/sjis.c \
$(MOSH_ONIG_DIR)/enc/iso8859_1.c \
$(MOSH_ONIG_DIR)/enc/iso8859_2.c \
$(MOSH_ONIG_DIR)/enc/iso8859_3.c \
$(MOSH_ONIG_DIR)/enc/iso8859_4.c \
$(MOSH_ONIG_DIR)/enc/iso8859_5.c \
$(MOSH_ONIG_DIR)/enc/iso8859_6.c \
$(MOSH_ONIG_DIR)/enc/iso8859_7.c \
$(MOSH_ONIG_DIR)/enc/iso8859_8.c \
$(MOSH_ONIG_DIR)/enc/iso8859_9.c \
$(MOSH_ONIG_DIR)/enc/iso8859_10.c \
$(MOSH_ONIG_DIR)/enc/iso8859_11.c \
$(MOSH_ONIG_DIR)/enc/iso8859_13.c \
$(MOSH_ONIG_DIR)/enc/iso8859_14.c \
$(MOSH_ONIG_DIR)/enc/iso8859_15.c \
$(MOSH_ONIG_DIR)/enc/iso8859_16.c \
$(MOSH_ONIG_DIR)/enc/euc_tw.c \
$(MOSH_ONIG_DIR)/enc/euc_kr.c \
$(MOSH_ONIG_DIR)/enc/big5.c \
$(MOSH_ONIG_DIR)/enc/gb18030.c \
$(MOSH_ONIG_DIR)/enc/koi8_r.c \
$(MOSH_ONIG_DIR)/enc/cp1251.c

