(import (rnrs)
        (mosh)
        (match)
        (mosh control)
        (only (srfi :1) first second)
        (mosh file))

;; Used for jit library.

(define (main args)
  (format #t ";; Don't edit this file which is generated by ~a\n" (first args))
  (let1 insn* (file->sexp-list (second args))
    (format #t "(define insn-count ~d)\n" (length insn*))
    (for-each-with-index
     (lambda (i insn-def)
       (match insn-def
         [('define-insn insn n)
          (format #t "(define $~a ~d)\n" insn i)]
         [x
          (error 'main "unknown insn-def" x)]))
     insn*)
    (format #t "(define insn-len-vec '#(")
    (for-each-with-index
     (lambda (i insn-def)
       (match insn-def
         [('define-insn insn n)
          (format #t "~d " n)]
         [x
          (error 'main "unknown insn-def" x)]))
     insn*)
    (format #t "))\n")
    (format #t "(define (insn-length insn) (vector-ref insn-len-vec (instruction->integer insn)))\n")))


(main (command-line))
