#!/usr/bin/env gosh
(use srfi-1)
(use file.util)
(use util.match)

(define (main args)
  (let1 free-vars (cdar (file->sexp-list (second args)))
    (write `(define *free-vars-decl*
              (quote ,(map
                       (lambda (free-var)
                         (match free-var
                           [(proc proc-body) proc]
                           [else free-var]))
                       free-vars)))))

;;   (define *free-vars* (with-input-from-file (second args)
;;     (lambda ()
;;       (cadr (third (read))))))
;;   (format #t ";; Do not edit this file generated by ~a.\n" (first args))
;;   (write `(define *free-vars-decl*
;;             (quote ,(map car *free-vars*))))
  0)
