(define %verbose #f)
(define %disable-acc #t)
(define %nmosh-portable-mode #f)
(define %nmosh-prefixless-mode #t)
(define %loadpath "lib.rnrs:lib.boot:../../../lib")
(define (%getpid) 0)
(load "compat-mosh-run.scm")
(load "runtime.scm")
(load "mosh-utils5.scm")
(load "BOOT1.exp")
(ex:load "build-run.ss")
