(library (nmosh gensym)
         (export gensym)
         (import (rnrs)
                 (primitives ex:generate-guid))
(define (gensym . sym?)
  (if (pair? sym?)
    (ex:generate-guid (car sym?))
    (ex:generate-guid 'RUNTIME)))
)
