MOSH=../mosh

test:
#	$(MOSH) -b tests/r6rs/run/eval.sps
#	$(MOSH) -b tests/r6rs/run/base.sps
#	$(MOSH) -b tests/r6rs/run/syntax-case.sps
#	$(MOSH) -b tests/r6rs/run/bytevectors.sps
#	$(MOSH) -b tests/r6rs/run/r5rs.sps
#	$(MOSH) -b tests/r6rs/run/conditions.sps
#	$(MOSH) -b tests/r6rs/run/reader.sps
	$(MOSH) -b tests/r6rs/run/unicode.sps
	$(MOSH) -b tests/r6rs/run/exceptions.sps
	$(MOSH) -b tests/r6rs/run/contrib.sps
	$(MOSH) -b tests/r6rs/run/mutable-strings.sps
	$(MOSH) -b tests/r6rs/run/mutable-pairs.sps
	$(MOSH) -b tests/r6rs/run/contrib.sps
	$(MOSH) -b tests/r6rs/run/programs.sps
	$(MOSH) -b tests/r6rs/run/control.sps
	$(MOSH) -b tests/r6rs/run/hashtables.sps
	$(MOSH) -b tests/r6rs/run/records/procedural.sps
	$(MOSH) -b tests/r6rs/run/lists.sps
	$(MOSH) -b tests/r6rs/run/enums.sps
	$(MOSH) -b tests/r6rs/run/sorting.sps
	$(MOSH) -b tests/r6rs/run/records/syntactic.sps
