MOSH=../mosh

test:
	$(MOSH) -b tests/r6rs/run/mutable-strings.sps
	$(MOSH) -b tests/r6rs/run/mutable-pairs.sps
	$(MOSH) -b tests/r6rs/run/contrib.sps
	$(MOSH) -b tests/r6rs/run/programs.sps
	$(MOSH) -b tests/r6rs/run/control.sps
	$(MOSH) -b tests/r6rs/run/hashtables.sps
	$(MOSH) -b tests/r6rs/run/records/procedural.sps
	$(MOSH) -b tests/r6rs/run/lists.sps
