#!/usr/bin/env gosh
(use srfi-1)

(define (main args)
  (define *free-vars* (with-input-from-file (second args)
    (lambda ()
      (cadr (third (read))))))
  (format #t ";; Do not edit this file generated by ~a.\n" (first args))
  (write `(define *free-vars-decl*
            (quote ,(map car *free-vars*))))
  0)
