(import (rnrs)
        (mosh)
        (srfi :1)
        (srfi :26)
        (srfi :98))

(define symbols '(
    (&assertion . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_438")
    (&condition . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_392")
    (&error . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_426")
    (&i/o-decoding . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_600")
    (&i/o-encoding . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_606")
    (&i/o-file-already-exists . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_540")
    (&i/o-file-does-not-exist . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_546")
    (&i/o-file-is-read-only . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_534")
    (&i/o-file-protection . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_528")
    (&i/o-filename . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_520")
    (&i/o-invalid-position . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_512")
    (&i/o-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_552")
    (&i/o-read . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_500")
    (&i/o-write . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_506")
    (&i/o . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_494")
    (&implementation-restriction . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_466")
    (&irritants . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_444")
    (&lexical . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_472")
    (&message . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_406")
    (&no-infinities . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1048")
    (&no-nans . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1054")
    (&non-continuable . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_460")
    (&serious . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_420")
    (&syntax . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_478")
    (&undefined . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_488")
    (&violation . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_432")
    (&warning . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_414")
    (&who . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_452")
    (abs . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_506")
    (acos . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_554")
    (and . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_388")
    (angle . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_576")
    (append . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_634")
    (apply . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_752")
    (asin . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_552")
    (assert . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_750")
    (assertion-violation . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_748")
    (assertion-violation? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_442")
    (assoc . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-4.html#node_idx_234")
    (assp . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-4.html#node_idx_232")
    (assq . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-4.html#node_idx_238")
    (assv . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-4.html#node_idx_236")
    (atan . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_556")
    (begin . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_418")
    (binary-port? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_648")
    (bitwise-and . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1066")
    (bitwise-arithmetic-shift-left . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1090")
    (bitwise-arithmetic-shift-right . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1092")
    (bitwise-arithmetic-shift . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1088")
    (bitwise-bit-count . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1074")
    (bitwise-bit-field . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1084")
    (bitwise-bit-set? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1080")
    (bitwise-copy-bit-field . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1086")
    (bitwise-copy-bit . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1082")
    (bitwise-first-bit-set . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1078")
    (bitwise-if . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1072")
    (bitwise-ior . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1068")
    (bitwise-length . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1076")
    (bitwise-not . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1064")
    (bitwise-reverse-bit-field . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1096")
    (bitwise-rotate-bit-field . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1094")
    (bitwise-xor . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1070")
    (boolean? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_328")
    (boolean=? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_598")
    (bound-identifier=? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-13.html#node_idx_1140")
    (buffer-mode . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_576")
    (buffer-mode? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_578")
    (bytevector->sint-list . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_118")
    (bytevector->string . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_630")
    (bytevector->u8-list . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_104")
    (bytevector->uint-list . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_116")
    (bytevector-copy . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_94")
    (bytevector-copy! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_92")
    (bytevector-fill! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_90")
    (bytevector-ieee-double-native-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_176")
    (bytevector-ieee-double-native-set! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_182")
    (bytevector-ieee-double-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_178")
    (bytevector-ieee-single-native-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_172")
    (bytevector-ieee-single-native-set! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_180")
    (bytevector-ieee-single-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_174")
    (bytevector-length . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_86")
    (bytevector-s16-native-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_130")
    (bytevector-s16-native-set! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_138")
    (bytevector-s16-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_126")
    (bytevector-s16-set! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_134")
    (bytevector-s32-native-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_146")
    (bytevector-s32-native-set! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_154")
    (bytevector-s32-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_142")
    (bytevector-s32-set! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_150")
    (bytevector-s64-native-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_162")
    (bytevector-s64-native-set! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_170")
    (bytevector-s64-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_158")
    (bytevector-s64-set! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_166")
    (bytevector-s8-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_98")
    (bytevector-s8-set! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_102")
    (bytevector-sint-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_110")
    (bytevector-sint-set! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_114")
    (bytevector-u16-native-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_128")
    (bytevector-u16-native-set! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_136")
    (bytevector-u16-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_124")
    (bytevector-u16-set! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_132")
    (bytevector-u32-native-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_144")
    (bytevector-u32-native-set! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_152")
    (bytevector-u32-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_140")
    (bytevector-u32-set! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_148")
    (bytevector-u64-native-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_160")
    (bytevector-u64-native-set! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_168")
    (bytevector-u64-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_156")
    (bytevector-u64-set! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_164")
    (bytevector-u8-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_96")
    (bytevector-u8-set! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_100")
    (bytevector-uint-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_108")
    (bytevector-uint-set! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_112")
    (bytevector? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_80")
    (bytevector=? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_88")
    (caar . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_616")
    (cadr . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_618")
    (call-with-bytevector-output-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_724")
    (call-with-current-continuation . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_754")
    (call-with-input-file . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_776")
    (call-with-output-file . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_778")
    (call-with-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_662")
    (call-with-string-output-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_728")
    (call-with-values . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_762")
    (call/cc . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_756")
    (car . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_612")
    (case-lambda . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-6.html#node_idx_262")
    (case . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_384")
    (cdddar . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_620")
    (cddddr . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_622")
    (cdr . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_614")
    (ceiling . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_530")
    (char->integer . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_670")
    (char-alphabetic? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_22")
    (char-ci<? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_14")
    (char-ci<=? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_18")
    (char-ci=? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_12")
    (char-ci>? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_16")
    (char-ci>=? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_20")
    (char-downcase . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_6")
    (char-foldcase . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_10")
    (char-general-category . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_34")
    (char-lower-case? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_30")
    (char-numeric? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_24")
    (char-title-case? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_32")
    (char-titlecase . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_8")
    (char-upcase . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_4")
    (char-upper-case? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_28")
    (char-whitespace? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_26")
    (char? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_336")
    (char<? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_676")
    (char<=? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_680")
    (char=? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_674")
    (char>? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_678")
    (char>=? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_682")
    (close-input-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_804")
    (close-output-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_806")
    (close-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_660")
    (command-line . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-11.html#node_idx_844")
    (complex? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_442")
    (cond . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_376")
    (condition-accessor . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_402")
    (condition-irritants . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_450")
    (condition-message . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_412")
    (condition-predicate . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_400")
    (condition-who . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_458")
    (condition . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_394")
    (condition? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_398")
    (cons . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_610")
    (cons* . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-4.html#node_idx_240")
    (cos . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_548")
    (current-error-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_736")
    (current-input-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_678")
    (current-output-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_734")
    (datum->syntax . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-13.html#node_idx_1146")
    (define-condition-type . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_404")
    (define-enumeration . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-15.html#node_idx_1262")
    (define-record-type . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_288")
    (define-syntax . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_358")
    (define . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_352")
    (delay . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-20.html#node_idx_1296")
    (delete-file . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-10.html#node_idx_840")
    (denominator . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_526")
    (display . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_828")
    (div-and-mod . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_508")
    (div . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_510")
    (div0-and-mod0 . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_514")
    (div0 . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_516")
    (do . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-6.html#node_idx_258")
    (dynamic-wind . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_764")
    (else . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_374")
    (else . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_380")
    (endianness . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_76")
    (enum-set->list . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-15.html#node_idx_1244")
    (enum-set-complement . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-15.html#node_idx_1258")
    (enum-set-constructor . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-15.html#node_idx_1242")
    (enum-set-difference . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-15.html#node_idx_1256")
    (enum-set-indexer . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-15.html#node_idx_1240")
    (enum-set-intersection . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-15.html#node_idx_1254")
    (enum-set-member? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-15.html#node_idx_1246")
    (enum-set-projection . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-15.html#node_idx_1260")
    (enum-set-subset? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-15.html#node_idx_1248")
    (enum-set-union . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-15.html#node_idx_1252")
    (enum-set-universe . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-15.html#node_idx_1238")
    (enum-set=? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-15.html#node_idx_1250")
    (environment . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-17.html#node_idx_1270")
    (eof-object . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_636")
    (eof-object? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_638")
    (eol-style . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_596")
    (eq? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_434")
    (equal-hash . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1218")
    (equal? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_436")
    (eqv? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_428")
    (error-handling-mode . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_614")
    (error? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_430")
    (eval . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-17.html#node_idx_1266")
    (even? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_482")
    (exact->inexact . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-20.html#node_idx_1286")
    (exact-integer-sqrt . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_562")
    (exact . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_462")
    (exact? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_456")
    (exists . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-4.html#node_idx_206")
    (exit . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-11.html#node_idx_846")
    (exp . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_540")
    (export . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-10.html#node_idx_270")
    (expt . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_564")
    (fields . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_290")
    (file-exists? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-10.html#node_idx_838")
    (file-options . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_574")
    (filter . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-4.html#node_idx_208")
    (find . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-4.html#node_idx_202")
    (finite? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_484")
    (fixnum->flonum . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1060")
    (fixnum-width . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_858")
    (fixnum? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_856")
    (fl- . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_990")
    (fl* . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_988")
    (fl/ . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_994")
    (fl+ . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_986")
    (fl<? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_956")
    (fl<=? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_958")
    (fl=? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_954")
    (fl>? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_960")
    (fl>=? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_962")
    (flabs . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_998")
    (flacos . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1038")
    (flasin . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1036")
    (flatan . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1040")
    (flceiling . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1018")
    (flcos . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1032")
    (fldenominator . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1014")
    (fldiv-and-mod . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1000")
    (fldiv . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1002")
    (fldiv0-and-mod0 . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1006")
    (fldiv0 . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1008")
    (fleven? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_974")
    (flexp . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1024")
    (flexpt . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1046")
    (flfinite? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_976")
    (flfloor . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1016")
    (flinfinite? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_978")
    (flinteger? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_964")
    (fllog . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1026")
    (flmax . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_982")
    (flmin . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_984")
    (flmod . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1004")
    (flmod0 . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1010")
    (flnan? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_980")
    (flnegative? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_970")
    (flnumerator . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1012")
    (flodd? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_972")
    (flonum? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_950")
    (floor . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_528")
    (flpositive? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_968")
    (flround . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1022")
    (flsin . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1030")
    (flsqrt . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1044")
    (fltan . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1034")
    (fltruncate . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1020")
    (flush-output-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_712")
    (flzero? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_966")
    (fold-left . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-4.html#node_idx_212")
    (fold-right . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-4.html#node_idx_214")
    (for-all . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-4.html#node_idx_204")
    (for-each . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_644")
    (force . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-20.html#node_idx_1304")
    (free-identifier=? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-13.html#node_idx_1142")
    (fx- . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_892")
    (fx-/carry . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_910")
    (fx* . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_890")
    (fx*/carry . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_912")
    (fx+ . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_888")
    (fx+/carry . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_908")
    (fx<? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_868")
    (fx<=? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_872")
    (fx=? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_864")
    (fx>? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_866")
    (fx>=? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_870")
    (fxand . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_916")
    (fxarithmetic-shift-left . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_940")
    (fxarithmetic-shift-right . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_942")
    (fxarithmetic-shift . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_938")
    (fxbit-count . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_924")
    (fxbit-field . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_934")
    (fxbit-set? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_930")
    (fxcopy-bit-field . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_936")
    (fxcopy-bit . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_932")
    (fxdiv-and-mod . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_896")
    (fxdiv . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_898")
    (fxdiv0-and-mod0 . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_902")
    (fxdiv0 . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_904")
    (fxeven? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_882")
    (fxfirst-bit-set . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_928")
    (fxif . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_922")
    (fxior . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_918")
    (fxlength . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_926")
    (fxmax . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_884")
    (fxmin . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_886")
    (fxmod . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_900")
    (fxmod0 . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_906")
    (fxnegative? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_878")
    (fxnot . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_914")
    (fxodd? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_880")
    (fxpositive? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_876")
    (fxreverse-bit-field . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_946")
    (fxrotate-bit-field . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_944")
    (fxxor . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_920")
    (fxzero? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_874")
    (gcd . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_520")
    (generate-temporaries . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-13.html#node_idx_1150")
    (get-bytevector-all . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_694")
    (get-bytevector-n . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_688")
    (get-bytevector-n! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_690")
    (get-bytevector-some . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_692")
    (get-char . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_696")
    (get-datum . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_708")
    (get-line . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_706")
    (get-string-all . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_704")
    (get-string-n . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_700")
    (get-string-n! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_702")
    (get-u8 . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_684")
    (greatest-fixnum . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_862")
    (guard . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_370")
    (hashtable-clear! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1204")
    (hashtable-contains? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1196")
    (hashtable-copy . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1200")
    (hashtable-delete! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1194")
    (hashtable-entries . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1210")
    (hashtable-equivalence-function . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1212")
    (hashtable-hash-function . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1214")
    (hashtable-keys . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1208")
    (hashtable-mutable? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1216")
    (hashtable-ref . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1190")
    (hashtable-set! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1192")
    (hashtable-size . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1188")
    (hashtable-update! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1198")
    (hashtable? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1186")
    (i/o-decoding-error? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_604")
    (i/o-encoding-error-char . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_612")
    (i/o-encoding-error? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_610")
    (i/o-error-filename . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_526")
    (i/o-error-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_558")
    (i/o-error-position . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_518")
    (i/o-error? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_498")
    (i/o-file-already-exists-error? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_544")
    (i/o-file-does-not-exist-error? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_550")
    (i/o-file-is-read-only-error? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_538")
    (i/o-file-protection-error? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_532")
    (i/o-filename-error? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_524")
    (i/o-invalid-position-error? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_516")
    (i/o-port-error? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_556")
    (i/o-read-error? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_504")
    (i/o-write-error? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_510")
    (identifier-syntax . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_796")
    (identifier? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-13.html#node_idx_1138")
    (if . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_366")
    (imag-part . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_572")
    (immutable . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_294")
    (implementation-restriction-violation? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_470")
    (import . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-10.html#node_idx_268")
    (inexact->exact . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-20.html#node_idx_1288")
    (inexact . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_460")
    (inexact? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_458")
    (infinite? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_486")
    (input-port? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_664")
    (integer->char . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_672")
    (integer-valued? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_454")
    (integer? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_448")
    (irritants-condition? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_448")
    (lambda . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_364")
    (latin-1-codec . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_590")
    (lcm . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_522")
    (least-fixnum . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_860")
    (length . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_632")
    (let-syntax . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_776")
    (let-values . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_410")
    (let . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_394")
    (let*-values . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_414")
    (let* . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_398")
    (letrec-syntax . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_782")
    (letrec . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_402")
    (letrec* . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_406")
    (lexical-violation? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_476")
    (library . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-10.html#node_idx_266")
    (list->string . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_714")
    (list->vector . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_738")
    (list-ref . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_640")
    (list-sort . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-5.html#node_idx_246")
    (list-tail . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_638")
    (list . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_630")
    (list? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_628")
    (log . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_542")
    (lookahead-char . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_698")
    (lookahead-u8 . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_686")
    (magnitude . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_574")
    (make-assertion-violation . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_440")
    (make-bytevector . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_82")
    (make-custom-binary-input-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_680")
    (make-custom-binary-input/output-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_762")
    (make-custom-binary-output-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_738")
    (make-custom-textual-input-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_682")
    (make-custom-textual-input/output-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_764")
    (make-custom-textual-output-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_740")
    (make-enumeration . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-15.html#node_idx_1236")
    (make-eq-hashtable . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1174")
    (make-eqv-hashtable . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1178")
    (make-error . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_428")
    (make-hashtable . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1182")
    (make-i/o-decoding-error . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_602")
    (make-i/o-encoding-error . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_608")
    (make-i/o-error . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_496")
    (make-i/o-file-already-exists-error . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_542")
    (make-i/o-file-does-not-exist-error . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_548")
    (make-i/o-file-is-read-only-error . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_536")
    (make-i/o-file-protection-error . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_530")
    (make-i/o-filename-error . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_522")
    (make-i/o-invalid-position-error . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_514")
    (make-i/o-port-error . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_554")
    (make-i/o-read-error . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_502")
    (make-i/o-write-error . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_508")
    (make-implementation-restriction-violation . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_468")
    (make-irritants-condition . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_446")
    (make-lexical-violation . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_474")
    (make-message-condition . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_408")
    (make-no-infinities-violation . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1050")
    (make-no-nans-violation . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1056")
    (make-non-continuable-violation . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_462")
    (make-polar . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_568")
    (make-record-constructor-descriptor . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_322")
    (make-record-type-descriptor . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_314")
    (make-rectangular . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_566")
    (make-serious-condition . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_422")
    (make-string . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_688")
    (make-syntax-violation . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_480")
    (make-transcoder . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_616")
    (make-undefined-violation . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_490")
    (make-variable-transformer . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-13.html#node_idx_1120")
    (make-vector . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_724")
    (make-violation . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_434")
    (make-warning . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_416")
    (make-who-condition . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_454")
    (map . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_642")
    (max . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_490")
    (member . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-4.html#node_idx_226")
    (memp . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-4.html#node_idx_224")
    (memq . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-4.html#node_idx_230")
    (memv . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-4.html#node_idx_228")
    (message-condition? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_410")
    (min . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_492")
    (mod . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_512")
    (mod0 . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_518")
    (modulo . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-20.html#node_idx_1294")
    (mutable . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_292")
    (nan? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_488")
    (native-endianness . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_78")
    (native-eol-style . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_598")
    (native-transcoder . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_622")
    (negative? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_478")
    (newline . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_824")
    (no-infinities-violation? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1052")
    (no-nans-violation? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1058")
    (non-continuable-violation? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_464")
    (nongenerative . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_304")
    (not . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_594")
    (null-environment . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-20.html#node_idx_1306")
    (null? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_346")
    (number->string . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_578")
    (number? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_334")
    (numerator . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_524")
    (odd? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_480")
    (opaque . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_302")
    (open-bytevector-input-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_672")
    (open-bytevector-output-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_720")
    (open-file-input-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_668")
    (open-file-input/output-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_758")
    (open-file-output-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_716")
    (open-input-file . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_800")
    (open-output-file . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_802")
    (open-string-input-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_674")
    (open-string-output-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_726")
    (or . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_390")
    (output-port-buffer-mode . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_714")
    (output-port? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_710")
    (pair? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_330")
    (parent-rtd . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_306")
    (parent . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_296")
    (partition . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-4.html#node_idx_210")
    (peek-char . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_812")
    (port-eof? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_666")
    (port-has-port-position? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_652")
    (port-has-set-port-position!? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_656")
    (port-position . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_654")
    (port-transcoder . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_644")
    (port? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_642")
    (positive? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_476")
    (procedure? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_342")
    (protocol . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_298")
    (put-bytevector . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_744")
    (put-char . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_748")
    (put-datum . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_756")
    (put-string . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_750")
    (put-u8 . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_742")
    (quasiquote . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_768")
    (quasisyntax . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-13.html#node_idx_1154")
    (quote . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_362")
    (quotient . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-20.html#node_idx_1290")
    (raise-continuable . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_378")
    (raise . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_376")
    (rational-valued? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_452")
    (rational? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_446")
    (rationalize . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_536")
    (read-char . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_808")
    (read . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_816")
    (real->flonum . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_952")
    (real-part . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_570")
    (real-valued? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_450")
    (real? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_444")
    (record-accessor . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_336")
    (record-constructor-descriptor . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_310")
    (record-constructor . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_332")
    (record-field-mutable? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_360")
    (record-mutator . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_338")
    (record-predicate . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_334")
    (record-rtd . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_344")
    (record-type-descriptor . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_308")
    (record-type-descriptor? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_320")
    (record-type-field-names . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_358")
    (record-type-generative? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_352")
    (record-type-name . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_346")
    (record-type-opaque? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_356")
    (record-type-parent . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_348")
    (record-type-sealed? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_354")
    (record-type-uid . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_350")
    (record? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_342")
    (remainder . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-20.html#node_idx_1292")
    (remove . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-4.html#node_idx_218")
    (remp . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-4.html#node_idx_216")
    (remq . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-4.html#node_idx_222")
    (remv . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-4.html#node_idx_220")
    (reverse . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_636")
    (round . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_534")
    (scheme-report-environment . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-20.html#node_idx_1308")
    (sealed . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_idx_300")
    (serious-condition? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_424")
    (set-car! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-18.html#node_idx_1274")
    (set-cdr! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-18.html#node_idx_1276")
    (set-port-position! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_658")
    (set! . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_372")
    (simple-conditions . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_396")
    (sin . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_546")
    (sint-list->bytevector . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_122")
    (sqrt . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_560")
    (standard-error-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_732")
    (standard-input-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_676")
    (standard-output-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_730")
    (string->bytevector . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_632")
    (string->list . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_712")
    (string->number . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_584")
    (string->symbol . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_652")
    (string->utf16 . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_186")
    (string->utf32 . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_190")
    (string->utf8 . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_184")
    (string-append . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_710")
    (string-ci-hash . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1222")
    (string-ci<? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_46")
    (string-ci<=? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_50")
    (string-ci=? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_44")
    (string-ci>? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_48")
    (string-ci>=? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_52")
    (string-copy . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_718")
    (string-downcase . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_38")
    (string-fill! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-19.html#node_idx_1282")
    (string-foldcase . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_42")
    (string-for-each . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_716")
    (string-hash . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1220")
    (string-length . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_694")
    (string-normalize-nfc . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_58")
    (string-normalize-nfd . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_54")
    (string-normalize-nfkc . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_60")
    (string-normalize-nfkd . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_56")
    (string-ref . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_696")
    (string-set! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-19.html#node_idx_1280")
    (string-titlecase . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_40")
    (string-upcase . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-2.html#node_idx_36")
    (string . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_692")
    (string? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_338")
    (string<? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_700")
    (string<=? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_704")
    (string=? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_698")
    (string>? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_702")
    (string>=? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_706")
    (substring . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_708")
    (symbol->string . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_648")
    (symbol-hash . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-14.html#node_idx_1224")
    (symbol? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_332")
    (symbol=? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_650")
    (syntax->datum . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-13.html#node_idx_1144")
    (syntax-case . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-13.html#node_idx_1124")
    (syntax-rules . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_786")
    (syntax-violation-form . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_484")
    (syntax-violation-subform . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_486")
    (syntax-violation . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-13.html#node_idx_1160")
    (syntax-violation? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_482")
    (syntax . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-13.html#node_idx_1134")
    (tan . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_550")
    (textual-port? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_646")
    (transcoded-port . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_650")
    (transcoder-codec . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_624")
    (transcoder-eol-style . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_626")
    (transcoder-error-handling-mode . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_628")
    (truncate . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_532")
    (u8-list->bytevector . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_106")
    (uint-list->bytevector . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_120")
    (undefined-violation? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_492")
    (unless . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-6.html#node_idx_256")
    (unquote-splicing . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_772")
    (unquote . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_770")
    (unsyntax-splicing . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-13.html#node_idx_1158")
    (unsyntax . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-13.html#node_idx_1156")
    (utf-16-codec . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_594")
    (utf-8-codec . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_592")
    (utf16->string . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_196")
    (utf32->string . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_198")
    (utf8->string . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-3.html#node_idx_194")
    (values . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_760")
    (vector->list . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_736")
    (vector-fill! . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_740")
    (vector-for-each . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_744")
    (vector-length . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_730")
    (vector-map . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_742")
    (vector-ref . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_732")
    (vector-set! . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_734")
    (vector-sort . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-5.html#node_idx_248")
    (vector-sort! . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-5.html#node_idx_250")
    (vector . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_728")
    (vector? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_340")
    (violation? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_436")
    (warning? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_418")
    (when . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-6.html#node_idx_254")
    (who-condition? . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_456")
    (with-exception-handler . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html#node_idx_368")
    (with-input-from-file . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_796")
    (with-output-to-file . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_798")
    (with-syntax . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-13.html#node_idx_1152")
    (write-char . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_820")
    (write . "http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_832")
    (zero? . "http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_474")
))

(define r6rs-dir (string-append (get-environment-variable "HOME") "/Desktop/r6rs/document/"))
(define out-dir (string-append (get-environment-variable "HOME") "/mosh/doc/text/"))

(define files '(("base.tex"
                 1
                 "Base Library"
                 ("(rnrs base (6))")
                 "The (rnrs base (6)) library, which exports many of the procedure and syntax bindings that are traditionally associated with Scheme.")
                ;; ("entry.tex"
;;                  6
;;                  "Entry format"
;;                  #f
;;                  "Bindings in the base library and the standard libraries are organized into entries.")
                ("bytevector.tex"
                 20
                 "Bytevectors"
                 ("(rnrs bytevectors (6))")
                 "Many applications deal with blocks of binary data by accessing them in various ways—extracting signed or unsigned numbers of various sizes.\n\n Therefore, the (rnrs bytevectors (6))library provides a single type for blocks of binary data with multiple ways to access that data. It deals with integers and floating-point representations in various sizes with specified endianness.")
                ("list.tex"
                 30
                 "List utilities"
                 ("(rnrs lists (6))")
                 "The (rnrs lists (6)) library contains various useful procedures that operate on lists.")
                ("sort.tex"
                 40
                 "Sorting"
                 ("(rnrs sorting (6))")
                 "The (rnrs sorting (6))library for sorting lists and vectors.")
                ("control.tex"
                 50
                 "Control structures"
                 ("(rnrs control (6))")
                 "The (rnrs control (6)) library provides useful control structures.")
                ("records.tex"
                 60
                 "Records"
                 ("(rnrs records syntactic (6))" "(rnrs records procedural (6))" "(rnrs records inspection (6))")
                 "Abstractions for creating new data types representing records.")
                ("exc.tex"
                 70
                 "Exceptions and conditions"
                 ("(rnrs exceptions (6))")
                 "Exception-handling and exception-raising constructs provided by the (rnrs exceptions (6))library.")
                ("iocond.tex"
                 81
                 "Condition types"
                 #f
                 "I/O condtion types.")
                ("portio.tex"
                 82
                 "Port I/O"
                 ("(rnrs io ports (6))")
                 "The (rnrs io ports (6)) library defines an I/O layer for conventional, imperative buffered input and output.")
                ("convio.tex"
                 83
                 "Simple I/O"
                 ("(rnrs io simple (6))")
                 "The (rnrs io simple (6)) library provides a somewhat more convenient interface for performing textual I/O on ports.")
                ("files.tex"
                 90
                 "File system"
                 ("(rnrs files (6))")
                 "The (rnrs files (6)) library for operations on the file system.")
                ("programlib.tex"
                 100
                 "Command-line access and exit values"
                 ("(rnrs programs (6))")
                 "Command-line access and exit values")
                ("arith.tex"
                 110
                 "Arithmetic"
                 #f
                 "More specialized numerical operations: fixnum and flonum arithmetic, as well as bitwise operations on exact integer objects.")
                ("syntax-case.tex"
                 120
                 "syntax-case"
                 ("(rnrs syntax-case (6))")
                 "The (rnrs syntax-case (6))library provides support for writing low-level macros in a high-level style, with automatic syntax checking, input destructuring, output restructuring, maintenance of lexical scoping and referential transparency (hygiene), and support for controlled identifier capture.")
                ("hashtable.tex"
                 130
                 "Hashtables"
                 ("(rnrs hashtables (6))")
                 "The (rnrs hashtables (6)) library provides a set of operations on hashtables.")
                ("enum.tex"
                 140
                 "Enumerations"
                 ("(rnrs enums (6))")
                 "The (rnrs enums (6)) library for dealing with enumerated values and sets of enumerated values.")
                ("eval.tex"
                 160
                 "eval"
                 ("(rnrs eval (6))")
                 "The (rnrs eval (6)) library allows a program to create Scheme expressions as data at run time and evaluate them.")
                ("setcar.tex"
                 170
                 "Mutable pairs"
                 ("(rnrs mutable-pairs (6))")
                 "The (rnrs mutable-pairs (6))library allow new values to be assigned to the car and cdr fields of previously allocated pairs.")
                ("stringset.tex"
                 180
                 "Mutable strings"
                 ("(rnrs mutable-strings (6))l")
                 "The string-set! procedure provided by the (rnrs mutable-strings (6))library allows mutating the characters of a string in-place.")
                ("r5rscompat.tex"
                 190
                 "R5RS compatibility"
                 ("(rnrs r5rs (6))")
                 "The (rnrs r5rs (6)) library provides some functionality of the preceding revision of this report that was omitted from the main part of the current report.")
                ))


(define (adjust-args args-string)
  (if args-string
      (map string->symbol
           (map (lambda (x)
                  (cond
                   [(string=? x "\\dotsfoo") "..."]
                   [(string=? x "$\\ldots$") "..."]
                   ;; hyper{test} => test
                   ;; hyperi{exp} => exp1
                   ;; hyperii{exp} => exp2
                   [(#/hyper(i*){(.*)}/ x) => (lambda (m)
                                                (if (m 1) ;; count i
                                                    (format "~a~a" (m 2) (string-length (m 1)))
                                                    (m 2)))]
                   [(#/var(i*){(.*)}/ x) => (lambda (m)
                                              (if (m 1) ;; count i
                                                  (format "~a~a" (m 2) (string-length (m 1)))
                                                  (m 2)))]
                   [(#/varn{(.*)}/ x) => (lambda (m) (format "~an" (m 1)))]
                   [else x]))
                (remp (cut string=? <> "") (string-split args-string #\space))))
      '()))

(define (file->prot* file)
  (let ([line* (file->list file)])
     (map
      (lambda (x)
        (list (string->symbol (x 1))
              (adjust-args (x 2))))
      (remq #f (append (map #/proto{([^}]+)}{(.*)}{procedure}/ line*)
                       (map #/proto{([^}]+)}{(.*)}{.+exprtype}/ line*))

     ))))

(for-each
 (lambda (file)
   (format (current-error-port) "~a\n" (first file))
   (with-output-to-file (string-append out-dir (first file) ".txt")
     (lambda ()
   (let ([proto* (file->prot* (string-append r6rs-dir (first file)))])
     (format #t "Title: ~a\n\n~a\n\n" (third file) (fifth file))
     (if (fourth file) ;; library-name
         (for-each (lambda (x) (format #t "library: ~a\n\n" x)) (fourth file))
         (format (current-error-port) "~a : library name not specified\n" (first file)))
     (for-each
      (lambda (prot)
        (format (current-error-port) "~a\n" prot)
        (format #t
"Function: ~a

See <~a>

Prototype:
> ~a\n\n\n"
        (car prot) (assoc-ref symbols (car prot)) `(,(car prot) ,@(cadr prot)))
        )
      proto*)
     ))))
 files)
