;;
;;   Copyright (c) 2008  Higepon(Taro Minowa)  <higepon@users.sourceforge.jp>
;;
;;   Redistribution and use in source and binary forms, with or without
;;   modification, are permitted provided that the following conditions
;;   are met:
;;
;;   1. Redistributions of source code must retain the above copyright
;;      notice, this list of conditions and the following disclaimer.
;;
;;   2. Redistributions in binary form must reproduce the above copyright
;;      notice, this list of conditions and the following disclaimer in the
;;      documentation and/or other materials provided with the distribution.
;;
;;   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
;;   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
;;   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
;;   A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
;;   OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
;;   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
;;   TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
;;   PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
;;   LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
;;   NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
;;   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
;;
(import (rnrs)
        (mosh string)
        (srfi-1)
        (mosh file))

(define (main args)
;; (display ((#/([^\;]+)\;\s*[^\;]+\;\s([^\;]+)\;/ "0390; 0390; 0399 0308 0301; 0399 0308 0301; # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS") 2))
;;   (exit)
  (format #t ";; Do not edit this file which generated by ~a.\n;;\n" (first args))
  (display "(define special-uppercase-list '(")
  (let loop ([lines (file->list "data/SpecialCasing.txt")]
             [index 0])
    (cond
     [(null? lines) (display "))")]
     [;(#/([\dA-F]+)\;\s*[\dA-F]+\;\s([\dA-F\s]+)\;/ (car lines))
      (#/([\dA-F]+)\;\s*[\dA-F\s]+\;\s*([\dA-F\s]+)\;\s*[\dA-F\s]+\;\s*#/ (car lines))
      => (lambda (match)
           (format #t "~a(~a . ~a)"
                   (if (zero? (mod index 5)) #\newline " ")
                   (string->number (match 1) 16)
                   (map (lambda (x) (string->number x 16)) (string-split (match 2) #\space))
                   )
           (loop (cdr lines) (+ index 1)))]
     [else
      (loop (cdr lines) index)])))

(main (command-line))
