(define-c-defined-const AF_INET)
(define-c-defined-const AF_INET6)
(define-c-defined-const AF_UNSPEC)
(define-c-defined-const SOCK_STREAM)
(define-c-defined-const SOCK_DGRAM)
(define-c-defined-const SOCK_RAW)
(define-c-defined-const AI_ADDRCONFIG)
(define-c-defined-const AI_ALL)
(define-c-defined-const AI_CANONNAME)
(define-c-defined-const AI_NUMERICHOST)
(define-c-defined-const AI_NUMERICSERV)
(define-c-defined-const AI_PASSIVE)
(define-c-defined-const AI_V4MAPPED)
(define-c-defined-const IPPROTO_TCP)
(define-c-defined-const IPPROTO_UDP)
(define-c-defined-const IPPROTO_RAW)
(define-c-defined-const SHUT_RD)
(define-c-defined-const SHUT_WR)
(define-c-defined-const SHUT_RDWR)
(define-c-defined-const MSG_OK)
(define-c-defined-const MSG_STARTED)
(define-c-defined-const MSG_INTERRUPTED)
(define-c-defined-const MSG_TIMER)
(define-c-defined-const MSG_READ_READY)
(define-c-defined-const MSG_WRITE_READY)
(define-c-defined-const MSG_TEXT)
;; signals
(define-c-defined-const SIGHUP)
(define-c-defined-const SIGINT)
(define-c-defined-const SIGQUIT)
(define-c-defined-const SIGILL)
(define-c-defined-const SIGTRAP)
(define-c-defined-const SIGABRT)
(define-c-defined-const SIGEMT)
(define-c-defined-const SIGFPE)
(define-c-defined-const SIGKILL)
(define-c-defined-const SIGBUS)
(define-c-defined-const SIGSEGV)
(define-c-defined-const SIGSYS)
(define-c-defined-const SIGPIPE)
(define-c-defined-const SIGALRM)
(define-c-defined-const SIGTERM)
(define-c-defined-const SIGURG)
(define-c-defined-const SIGTHR)
(define-c-defined-const SIGUSR1)
(define-c-defined-const SIGUSR2)
(define-c-defined-const SIGCHLD)
(define-c-defined-const SIGCONT)
(define-c-defined-const SIGSTOP)
(define-c-defined-const SIGTSTP)
(define-c-defined-const SIGTTIN)
(define-c-defined-const SIGTTOU)
(define-c-defined-const SIGPOLL)
(define-c-defined-const SIGPROF)
(define-c-defined-const SIGSYS)
(define-c-defined-const SIGVTALRM)
(define-c-defined-const SIGXCPU)
(define-c-defined-const SIGXFSZ)
(define-c-defined-const SIGIO)
(define-c-defined-const SIGPWR)
(define-c-defined-const SIGINFO)
(define-c-defined-const SIGLOST)
(define-c-defined-const SIGWINCH)

(define-size-of char)
(define-size-of bool)
(define-size-of short)
(define-size-of unsigned short)
(define-size-of int)
(define-size-of unsigned int)
(define-size-of long)
(define-size-of unsigned long)
(define-size-of unsigned long long)
(define-size-of long long)
(define-size-of void*)
(define-size-of size_t)
(define-size-of float)
(define-size-of double)
(define-align-of char)
(define-align-of bool)
(define-align-of short)
(define-align-of unsigned short)
(define-align-of int)
(define-align-of unsigned int)
(define-align-of long)
(define-align-of unsigned long)
(define-align-of unsigned long long)
(define-align-of long long)
(define-align-of void*)
(define-align-of size_t)
(define-align-of float)
(define-align-of double)
(define-align-of int8_t)
(define-align-of int16_t)
(define-align-of int32_t)
(define-align-of int64_t)
